### ISSUE TITLE
Cannot get this module work with ADFS 2016

### ISSUE THREAD

**Issue by AsierBadiolaVersia** [jobec/django-auth-adfs#105]
We have installed and configured the module an ADFS 2016 as indicated in the documentation (https://django-auth-adfs.readthedocs.io/en/latest/adfs_4.0_config_guide.html) but we cannot get it work.

We've configured the Application Group as indicated and added the configuration to the settings.py file (ADFS_AUTH)

When we try to access the login page, we get an error because the module is trying to access a URL that does noyt really exists.

Is there any missing part in the documentation?
Is there a way we import the required configuration from the ADFS Metadata file

It seems that it goes directly to `_load_openid_config()` and it does not run the part of the code where the adfs federationMetadata is loaded (`_load_federation_metadata()` ) (in the `config.py` file of the module):

```python
            try:
                loaded = self._load_openid_config()
                self._mode = "openid_connect"
            except ConfigLoadError:
                loaded = self._load_federation_metadata()
                self._mode = "oauth2"
```

Our configuration (`settings.py`):

```python
AUTH_ADFS = {
    "SERVER": "our.company.com",
    "CLIENT_ID": "our-client-id",
    "RELYING_PARTY_ID": "our-client-id",
    # Make sure to read the documentation about the AUDIENCE setting
    # when you configured the identifier as a URL!
    "AUDIENCE": "microsoft:identityserver:our-client-id",
    # "CA_BUNDLE": "certification.pem",
    "CLAIM_MAPPING": {"first_name": "given_name",
                      "last_name": "family_name",
                      "email": "email"},
    "USERNAME_CLAIM": "winaccountname",
    "GROUP_CLAIM": "group"
}

```

![MicrosoftTeams-image (16)](https://user-images.githubusercontent.com/46448986/87934101-b2135680-ca8e-11ea-9d46-8bdee6d93978.png)

**Comment by JonasKs** [comment]
Looking at it though, does the URL it tries to reach exist? If it does and you can reach it, is there a firewall between your app and the ADFS?

**Comment by AsierBadiolaVersia** [comment]
The logging would be:

```
Environment:


Request Method: GET
Request URL: https://*******.herokuapp.com/oauth2/login?next=/

Django Version: 3.0.8
Python Version: 3.7.8
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_auth_adfs']
Installed Middleware:
('whitenoise.middleware.WhiteNoiseMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django_auth_adfs.middleware.LoginRequiredMiddleware')



Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 417, in _make_request
    httplib_response = conn.getresponse(buffering=True)

During handling of the above exception (getresponse() got an unexpected keyword argument 'buffering'), another exception occurred:
  File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
    # Permission is hereby granted, free of charge, to any person obtaining a copy
  File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/app/.heroku/python/lib/python3.7/http/client.py", line 1354, in getresponse
    response.begin()
  File "/app/.heroku/python/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/app/.heroku/python/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/app/.heroku/python/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/app/.heroku/python/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/app/.heroku/python/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)

During handling of the above exception (The read operation timed out), another exception occurred:
  File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value

During handling of the above exception (HTTPSConnectionPool(host='our.company.com', port=443): Read timed out. (read timeout=5)), another exception occurred:
  File "/app/.heroku/python/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 765, in urlopen
    **response_kw
  File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 765, in urlopen
    **response_kw
  File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 765, in urlopen
    **response_kw
  File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))

During handling of the above exception (HTTPSConnectionPool(host='our.company.com', port=443): Max retries exceeded with url: /adfs/.well-known/openid-configuration (Caused by ReadTimeoutError("HTTPSConnectionPool(host='our.company.com', port=443): Read timed out. (read timeout=5)"))), another exception occurred:
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.7/site-packages/django_auth_adfs/views.py", line 73, in get
    return redirect(provider_config.build_authorization_endpoint(request))
  File "/app/.heroku/python/lib/python3.7/site-packages/django_auth_adfs/config.py", line 307, in build_authorization_endpoint
    self.load_config()
  File "/app/.heroku/python/lib/python3.7/site-packages/django_auth_adfs/config.py", line 192, in load_config
    loaded = self._load_openid_config()
  File "/app/.heroku/python/lib/python3.7/site-packages/django_auth_adfs/config.py", line 224, in _load_openid_config
    response = self.session.get(config_url, timeout=settings.TIMEOUT)
  File "/app/.heroku/python/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/app/.heroku/python/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/.heroku/python/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/app/.heroku/python/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)

Exception Type: ConnectionError at /oauth2/login
Exception Value: HTTPSConnectionPool(host='our.company.com', port=443): Max retries exceeded with url: /adfs/.well-known/openid-configuration (Caused by ReadTimeoutError("HTTPSConnectionPool(host='our.company.com', port=443): Read timed out. (read timeout=5)"))

```

**Comment by JonasKs** [comment]
Are you able to reach `our.company.com/adfs/.well-known/openid-configuration` locally? Are you able to reach it from your Heroku app? It times out, I assume it’s because of a firewall?

**Comment by AsierBadiolaVersia** [comment]
Hello @JonasKs, I have tried reaching `our.company.com/adfs/.well-known/openid-configuration` via `curl` through Heroku and I get to it perfectly

**Comment by jobec** [comment]
And you run that curl from within the same server/container/whatever as the one Django is running in? Is it responding withing 5s when doing it with curl?

It all indicates a connection issue between Django and your ADFS server.

**Comment by AsierBadiolaVersia** [comment]
Hello @jobec. 

Yes, we run that curl from the same server and we didn't reach to it. Eventually, we have discarded connecting ADFS via Django and we are exploring other ways to do it, but thanks for your help.
