### ISSUE TITLE
Database Integrity Error when using multiple workers/threads with Gunicorn

### ISSUE THREAD

**Issue by JonasKs** [jobec/django-auth-adfs#93]
I'm developing a [middleware](https://github.com/JonasKs/django-guid/tree/skip_cleanup) where I store a GUID for each request and was doing tests on how this performs with gunicorn settings such as `--threads 4` and `-w 4`. ([Docs](https://docs.gunicorn.org/en/stable/settings.html))

Together with this, I do a lot of requests with [`ab`](https://httpd.apache.org/docs/2.4/programs/ab.html). Example string: `ab -p post.txt -c 4 -n 50 -T application/json -H "Authorization: Bearer <access_token> http://127.0.0.1:8000/api/v1/test`

This means I'm sending concurrent requests towards the Django app, which now has multiple threads instead of the sync single threaded default Gunicorn settings. Now, with my middleware it's easy to track each request and when things goes wrong: (Filtered out GUID `55f7b768046149e5aecf723cbbb053b4`) 

```py
INFO 2020-01-10 14:13:20,188 [None] django_guid.middleware No Correlation-ID found in the header. Added Correlation-ID: 55f7b768046149e5aecf723cbbb053b4
WARNING 2020-01-10 14:13:20,282 [55f7b768046149e5aecf723cbbb053b4] django_auth_adfs Claim 'family_name' for user field 'last_name' was not found in the access token for user 'MyUser'. Field is not required and will be left empty
WARNING 2020-01-10 14:13:20,284 [55f7b768046149e5aecf723cbbb053b4] django_auth_adfs Claim 'email' for user field 'email' was not found in the access token for user 'MyUser'. Field is not required and will be left empty
ERROR 2020-01-10 14:13:20,337 [55f7b768046149e5aecf723cbbb053b4] django.request Internal Server Error: /api/v1/apic/flash
Traceback (most recent call last):
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry '25-680' for key 'auth_user_groups_user_id_group_id_94350c0c_uniq'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 493, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 410, in initial
    self.perform_authentication(request)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/rest_framework/request.py", line 220, in user
    self._authenticate()
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/rest_framework/request.py", line 373, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django_auth_adfs/rest_framework.py", line 40, in authenticate
    user = authenticate(access_token=auth[1])
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django_auth_adfs/backend.py", line 285, in authenticate
    user = self.process_access_token(access_token)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django_auth_adfs/backend.py", line 95, in process_access_token
    self.update_user_groups(user, claims)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django_auth_adfs/backend.py", line 201, in update_user_groups
    user.groups.add(group)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 936, in add
    self._add_items(
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 1080, in _add_items
    self.through._default_manager.using(db).bulk_create([
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/models/query.py", line 474, in bulk_create
    ids = self._batched_insert(objs_without_pk, fields, batch_size, ignore_conflicts=ignore_conflicts)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1211, in _batched_insert
    self._insert(item, fields=fields, using=self.db, ignore_conflicts=ignore_conflicts)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1368, in execute_sql
    cursor.execute(sql, params)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/myuser/myproject/venv/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry '25-680' for key 'auth_user_groups_user_id_group_id_94350c0c_uniq'")

```

EDIT: I assume this potentially can happen in a loadbalanced environment (such as a multi-pod kubernetes set up) too.

**Comment by jobec** [comment]
Yeah, that's a race condition. Not sure though how to fix it. Maybe wrapping it in transactions or so.

You can also trigger it with Django's default authentication backend is you would trigger a login requests at almost the same time with the same user. Of course, there it won't dynamically update the database on every login.

In a load balanced environment, this would not necessarily happen. Because you wouldn't expect the same user to log in more then once at exactly the same time.

**Comment by JonasKs** [comment]
Hmmm, I see. We encounter it more and more, even when developing locally with DRF and doing multiple requests to different APIs. Could a solution be to save a hash of the JWT token to the database for x minutes? If that hash is found, don’t update the user?

**Comment by JonasKs** [comment]
I guess that potentially would cause the same race condition. It’s a though one, and it’s a shame since we’ve seen it happen on just two normal requests at the same time from a web browser. Async too stong.

**Comment by jobec** [comment]
That feature is partially inspired by how django-auth-ldap works. I'll have a look at how they solved this. Might be as easy as ignoring the integrity exceptions.

**Comment by JonasKs** [comment]
Maybe that’s just as good. At the moment it triggers a 500, which is quite annoying. 

I’ll be able to test on Monday morning how it behaves for me with ignoring them, and can gladly raise a PR if that works for us.

**Comment by jobec** [comment]
djang-auth-ldap determines the exact groups that the user should be in and sets them in one operation with `set()`
https://github.com/django-auth-ldap/django-auth-ldap/blob/99090772cd7275d2ff6bbb27816894aa89cdba49/django_auth_ldap/backend.py#L785

https://docs.djangoproject.com/en/3.0/ref/models/relations/#django.db.models.fields.related.RelatedManager.set

**Comment by JonasKs** [comment]
I see. Basically rewrite [this](https://github.com/jobec/django-auth-adfs/blob/master/django_auth_adfs/backend.py#L202) to use `set()` instead?

**Comment by jobec** [comment]
Exactly

**Comment by jobec** [comment]
It's even easier. By using set, there is no need anymore for the logic that determines the groups to add and delete. `set()` does that in one go.

**Comment by JonasKs** [comment]
I'll do it on Monday if you don't mind.

I'd also like to change all your `logger` functions that uses `'string {}'.format(variable)`  to be `'string %s', variable` instead. The reason behind is explained well in my own [issue](https://github.com/JonasKs/django-guid/issues/18). I'd like to implement Sentry in my stack.

**Comment by jobec** [comment]
Please open a separate issue for that logging string refactoring. It'll be easier to review.

As for the auto publish to PyPI: I'm looking into that already. But there's more to it then just building and pushing to PyPI. Most effort is actually in writing a changelog and updating version numbers.

**Comment by JonasKs** [comment]
Absolutely. I'll create two separate pull requests on Monday or tomorrow. 🚀 

As for a PyPi pipeline I have one [here](https://github.com/JonasKs/django-guid/blob/master/.github/workflows/publish_to_pypi.yml). It has the same issues with creating another version in `__init__.py`, but maybe an implementation with [python-semanticversion](https://github.com/rbarrois/python-semanticversion) could be done.
